### ISSUE TITLE
What music do you listen to while programming?

### ISSUE THREAD

**Issue by SamVerschueren** [jfmengels/ama#10]
What brings you into the zone :)?

**Comment by jfmengels** [comment]
I usually listen to pop / rock music. `Florence + The Machine` is one of my favorite artists if that is any guidance, and would definitely recommend checking out.

There isn't anything that gets me in "the zone", it's the same music that I listen when I code, and listen to when I do other things on my laptop.

At work I usually listen to Spotify's `Discover Weekly` playlist to discover things I like. I don't know if it gives everybody the same list or not, but there is often a few songs that I really like in there (in between all those ads...).
