### ISSUE TITLE
What is your longest coding streak?

### ISSUE THREAD

**Issue by sholladay** [jfmengels/ama#11]
Most of us have pulled all nighters, but some even further. What was your longest and more importantly, what were you working on?

**Comment by jfmengels** [comment]
If you mean in successive "hours", I did a three day game jam a few years back with two other devs, with something like a two hour sleep break somewhere. We did not know the tools to make the game much, and in all the result was pretty terrible and we ended up not even submitting it.

If you talk about successive days, my longest streak was from March 14th until May 27th, so a 74-day streak (98 day streak from February 19th if we omit March 13th). I was trying to contribute at least once a day, and I stopped soon after GitHub stopped indicating streak record the number of days (somewhere in May). Truth be told, I felt a bit liberated afterwards, and I wonder how I would have done it during some of my holidays (didn't take any during that streak) and just to spend the evening doing something else. My social life was not very active in that period, and I was sometimes a bit fidgety about being able to make my daily contribution on some occasions.

I ended doing a whole lot of things in that period (working on different ESLint plugins mostly), but recently I have had a lot of trouble both finding time and motivation (or rather, both of them together) and have been neglecting some issues in the last month. Which does not make me feel good at all. In hindsight, what I probably should have done more is to incite people to contribute to the projects I contributed to, give them commit/publish access and let them be able to manage things by themselves.

Thanks for the question :)
