### ISSUE TITLE
How did you get interested in ASTs?

### ISSUE THREAD

**Issue by sindresorhus** [jfmengels/ama#2]
(AST → Abstract Syntax Tree)

**Comment by jfmengels** [comment]
Beginning of 2016, Lodash v4 came out, and along with it brought `lodash/fp`, which I thought was really cool. Unfortunately, the docs for it were really lacking, compared to the official docs.

Then I thought that I could probably use that tool `jscodeshift` I heard about to update all the examples, so I did that, and played with it for a while to get it right. I made a [PR](https://github.com/lodash/lodash/pull/1897) which got accepted, but soon-ish pulled out as it was too complicated, and there were still plenty of examples that were not ok. The result was [this gist](https://gist.github.com/jfmengels/6b973b69c491375117dc), which I update occasionally.

Even up to this date, https://github.com/lodash/lodash/wiki/FP-Guide is the only official thing. Though my gist is sometimes linked to by its maintainer.

If you want to know how I started in open source, I'd tell you the same story :)
Well you can add to that that about a month later, I was on a holiday, and in my spare time I saw a new repo named `eslint-plugin-ava` and thought that I could have fun with it: https://github.com/avajs/eslint-plugin-ava/pull/11. Afterwards, that plugin got plenty of new rule ideas and I kept working on those.

**Comment by sindresorhus** [comment]
You can move the last part into https://github.com/jfmengels/ama/issues/8 ;)
