### ISSUE TITLE
What languages do you speak?

### ISSUE THREAD

**Issue by sindresorhus** [jfmengels/ama#4]

**Comment by jfmengels** [comment]
- Dutch
- French
- English
- German. Well, I was very good at it at school since it is very close to dutch, but I forgot most of it since then. I still occasionally rehearse the following sentence: "Ich habe seit einige Jahren kein Deutsch mehr gesprochen, deshalb ist mein Deutsch jetzt schlecht."

**Comment by lue-bird** [comment]
Impressive.
FYI, the correct phrase would be either "Ich habe seit einige**n** Jahren kein Deutsch mehr gesprochen, deshalb ist mein Deutsch jetzt schlecht" or "Ich habe einige Jahre (lang) kein Deutsch mehr gesprochen, deshalb ist mein Deutsch jetzt schlecht"
I'd probably say "Die letzten Jahre hab ich nie Deutsch gesprochen. Ich denke meiste hab ich inzwischen vergessen"
