### ISSUE TITLE
Until recently I thought your name was Jeff Mengels. How do you feel about that?

### ISSUE THREAD

**Issue by sindresorhus** [jfmengels/ama#5]
Probably because reading your username `jfmengels` out loud makes it sound like Jeff Mengels.

When we implemented the full name thing in Refined GitHub I realized it was not.

**Comment by jfmengels** [comment]
@jamestalmage probably didn't help on that front https://youtu.be/YRvrPkXBwdo?t=1475 :sweat_smile: 

Before I saw that video (and burst into laughter), I absolutely never thought that people would confuse it like that. In a way, that might be a good thing as nobody would remember Jeroen.

By the way, Jeff Mengels is now my official false name whenever I will need to give a false american sounding name.

I'm totally cool with that fact, but I hope people won't call me out in public with that name :sweat_smile:
